services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\BitrixMenuBuilderBundle\Services\MenuManagerCachedFacade: ~
  Prokl\BitrixMenuBuilderBundle\Services\MenuManagerFacade: ~